name = "libigl_jll"
uuid = "b22ceafb-42ac-50cb-bbfc-91fa172c9161"
version = "2.6.0+0"

[deps]
Libglvnd_jll = "7e76a0d4-f3c7-5321-8279-8d96eeed0f29"
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
GMP_jll = "781609d7-10c4-51f6-84f2-b8444358ff6d"
MPFR_jll = "3a97d323-0669-5f0c-9066-3539efd106a3"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
OpenBLAS32_jll = "656ef2d0-ae68-5445-9ca0-591084a874a2"
ICU_jll = "a51ab1cf-af8e-5615-a023-bc2c838bba6b"
GLFW_jll = "0656b61e-2033-5cc2-a64a-77c0f6c09b89"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
JLLWrappers = "1.7.0"
julia = "1.6"
Libdl = "< 0.0.1, 1"
Artifacts = "< 0.0.1, 1"
